const KEY='dollar-app-v1';
const defaultData={activities:[],baths:[],weights:[],vaccines:[],reminders:{bath:'',weight:''},unit:'kg'};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(defaultData);
let viewDate=new Date(); let selectedDate='';
const $=s=>document.querySelector(s); const pad=n=>String(n).padStart(2,'0');
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const formatDate=s=>new Date(`${s}T12:00:00`).toLocaleDateString('zh-CN',{month:'long',day:'numeric',year:'numeric'});
function save(){localStorage.setItem(KEY,JSON.stringify(data));render();}
function openSheet(html){$('#bottom-sheet').innerHTML=html;$('#bottom-sheet').classList.remove('hidden');$('#sheet-backdrop').classList.remove('hidden');}
function closeSheet(){$('#bottom-sheet').classList.add('hidden');$('#sheet-backdrop').classList.add('hidden');}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),1800)}
function renderCalendar(){const year=viewDate.getFullYear(),month=viewDate.getMonth();$('#month-title').textContent=`${year}年 ${month+1}月`;const start=new Date(year,month,1).getDay(),days=new Date(year,month+1,0).getDate(),today=iso(new Date());let html='';for(let i=0;i<start;i++)html+='<span class="day blank"></span>';for(let day=1;day<=days;day++){const date=`${year}-${pad(month+1)}-${pad(day)}`;const bath=data.baths.find(x=>x.date===date);const act=data.activities.find(x=>x.date===date);const type=bath?'bath':act?.type||'';html+=`<button class="day ${type} ${date===today?'today':''}" data-date="${date}">${day}</button>`}$('#calendar-grid').innerHTML=html;document.querySelectorAll('.day[data-date]').forEach(b=>b.onclick=()=>daySheet(b.dataset.date));}
function reminderText(date){if(!date)return'设置下次提醒';const diff=Math.ceil((new Date(`${date}T12:00:00`)-new Date())/86400000);return diff<0?'提醒已到期':diff===0?'今天':`${diff} 天后`;}
function renderHome(){renderCalendar();$('#bath-reminder-text').textContent=reminderText(data.reminders.bath);$('#weight-reminder-text').textContent=reminderText(data.reminders.weight);const last=[...data.weights].sort((a,b)=>b.date.localeCompare(a.date))[0];$('#latest-weight').textContent=last?`${last.value} ${data.unit}`:'还没有记录';}
function recordItem(title,sub,onEdit,onDelete){return `<div class="record"><div class="record-main"><strong>${title}</strong><small>${sub}</small></div><div class="record-actions"><button data-edit="${onEdit}">编辑</button><button data-delete="${onDelete}">删除</button></div></div>`}
function bindRecordActions(){document.querySelectorAll('[data-edit]').forEach(e=>e.onclick=()=>editByToken(e.dataset.edit));document.querySelectorAll('[data-delete]').forEach(e=>e.onclick=()=>confirmDelete(e.dataset.delete));}
function renderHealth(){const weights=[...data.weights].sort((a,b)=>a.date.localeCompare(b.date));let weightHtml='';if(weights.length>=3)weightHtml+=trendSvg(weights);weightHtml+=weights.length?`<div class="record-list">${weights.slice().reverse().map(x=>recordItem(`${x.value} ${data.unit}`,formatDate(x.date),`weight:${x.id}`,`weight:${x.id}`)).join('')}</div>`:'还没有体重记录';$('#weight-content').className=weights.length?'':'empty-state';$('#weight-content').innerHTML=weightHtml;const baths=[...data.baths].sort((a,b)=>b.date.localeCompare(a.date));$('#bath-content').className=baths.length?'':'empty-state';$('#bath-content').innerHTML=baths.length?`<div class="record-list">${baths.map(x=>recordItem('洗澡',formatDate(x.date),`bath:${x.id}`,`bath:${x.id}`)).join('')}</div>`:'还没有洗澡记录';const vaccines=[...data.vaccines].sort((a,b)=>b.date.localeCompare(a.date));$('#vaccine-content').className=vaccines.length?'':'empty-state';$('#vaccine-content').innerHTML=vaccines.length?`<div class="record-list">${vaccines.map(x=>recordItem(x.name,`${formatDate(x.date)}${x.next?' · 下次 '+formatDate(x.next):''}`,`vaccine:${x.id}`,`vaccine:${x.id}`)).join('')}</div>`:'还没有疫苗记录';$('#unit-label').textContent=data.unit;bindRecordActions();}
function trendSvg(items){const vals=items.map(x=>Number(x.value)),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;const pts=vals.map((v,i)=>`${i*(100/(vals.length-1))},${91-((v-min)/range)*68}`).join(' ');return `<div class="trend"><svg viewBox="-3 0 106 104" preserveAspectRatio="none"><path d="M0,95H100" stroke="#eee5dc"/><polyline points="${pts}" fill="none" stroke="#9bba7a" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${pts.split(' ').map(p=>`<circle cx="${p.split(',')[0]}" cy="${p.split(',')[1]}" r="3" fill="#9bba7a"/>`).join('')}</svg></div>`}
function render(){renderHome();renderHealth();}
function daySheet(date){selectedDate=date;const bath=data.baths.find(x=>x.date===date),act=data.activities.find(x=>x.date===date);let current='';if(bath)current+='<p class="sheet-subtitle">已记录：洗澡</p>';if(act)current+=`<p class="sheet-subtitle">已记录：${({walk:'遛狗',park:'狗公园',hike:'Hiking'})[act.type]}</p>`;openSheet(`<div class="sheet-handle"></div><h2 class="sheet-title">${formatDate(date)}</h2>${current||'<p class="sheet-subtitle">记录 Dollar 今天做了什么</p>'}<div class="activity-options"><button class="activity-option" data-act="walk">遛狗 <span>简单</span></button><button class="activity-option" data-act="park">狗公园 <span>中等</span></button><button class="activity-option" data-act="hike">Hiking <span>难</span></button><button class="activity-option" id="day-bath">洗澡 <span>护理</span></button></div><button class="sheet-secondary" id="close-sheet">取消</button>`);document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>{data.activities=data.activities.filter(x=>x.date!==date);data.activities.push({id:crypto.randomUUID(),date,type:b.dataset.act});save();closeSheet();toast('已添加记录')});$('#day-bath').onclick=()=>bathForm();$('#close-sheet').onclick=closeSheet;}
function bathForm(existing){openSheet(`<div class="sheet-handle"></div><h2 class="sheet-title">${existing?'编辑洗澡记录':'记录洗澡'}</h2><form id="bath-form" class="form"><label>洗澡日期<input required type="date" name="date" value="${existing?.date||selectedDate||iso(new Date())}"></label><label>下次洗澡提醒（可选）<input type="date" name="reminder" value="${data.reminders.bath||''}"></label><button class="form-submit">保存</button></form>${existing?`<button class="danger-button" id="delete-current">删除这条记录</button>`:''}<button class="sheet-secondary" id="close-sheet">取消</button>`);$('#bath-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(existing)data.baths=data.baths.filter(x=>x.id!==existing.id);data.baths.push({id:existing?.id||crypto.randomUUID(),date:f.get('date')});data.reminders.bath=f.get('reminder');save();closeSheet();toast('洗澡记录已保存')};$('#close-sheet').onclick=closeSheet;if(existing)$('#delete-current').onclick=()=>confirmDelete(`bath:${existing.id}`);}
function weightForm(existing){openSheet(`<div class="sheet-handle"></div><h2 class="sheet-title">${existing?'编辑体重':'记录体重'}</h2><form id="weight-form" class="form"><label>日期<input required type="date" name="date" value="${existing?.date||iso(new Date())}"></label><label>体重（${data.unit}）<input required step="0.1" min="0" type="number" name="value" value="${existing?.value||''}" placeholder="例如 12.4"></label><label>下次称重提醒（可选）<input type="date" name="reminder" value="${data.reminders.weight||''}"></label><button class="form-submit">保存</button></form>${existing?`<button class="danger-button" id="delete-current">删除这条记录</button>`:''}<button class="sheet-secondary" id="close-sheet">取消</button>`);$('#weight-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(existing)data.weights=data.weights.filter(x=>x.id!==existing.id);data.weights.push({id:existing?.id||crypto.randomUUID(),date:f.get('date'),value:f.get('value')});data.reminders.weight=f.get('reminder');save();closeSheet();toast('体重记录已保存')};$('#close-sheet').onclick=closeSheet;if(existing)$('#delete-current').onclick=()=>confirmDelete(`weight:${existing.id}`);}
function vaccineForm(existing){openSheet(`<div class="sheet-handle"></div><h2 class="sheet-title">${existing?'编辑疫苗':'添加疫苗'}</h2><form id="vaccine-form" class="form"><label>疫苗名称<input required name="name" value="${existing?.name||''}" placeholder="例如：狂犬病疫苗"></label><label>接种日期<input required type="date" name="date" value="${existing?.date||iso(new Date())}"></label><label>下次接种日期<input type="date" name="next" value="${existing?.next||''}"></label><label>备注<textarea name="note" placeholder="可选">${existing?.note||''}</textarea></label><button class="form-submit">保存</button></form>${existing?`<button class="danger-button" id="delete-current">删除这条记录</button>`:''}<button class="sheet-secondary" id="close-sheet">取消</button>`);$('#vaccine-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(existing)data.vaccines=data.vaccines.filter(x=>x.id!==existing.id);data.vaccines.push({id:existing?.id||crypto.randomUUID(),name:f.get('name'),date:f.get('date'),next:f.get('next'),note:f.get('note')});save();closeSheet();toast('疫苗记录已保存')};$('#close-sheet').onclick=closeSheet;if(existing)$('#delete-current').onclick=()=>confirmDelete(`vaccine:${existing.id}`);}
function editByToken(token){const [type,id]=token.split(':');const item=data[`${type}s`]?.find(x=>x.id===id);if(type==='weight')weightForm(item);if(type==='bath')bathForm(item);if(type==='vaccine')vaccineForm(item)}
function confirmDelete(token){const [type,id]=token.split(':');openSheet(`<div class="sheet-handle"></div><h2 class="sheet-title">删除这条记录？</h2><p class="sheet-subtitle">删除后无法恢复。</p><button class="danger-button" id="confirm-delete">确认删除</button><button class="sheet-secondary" id="close-sheet">取消</button>`);$('#confirm-delete').onclick=()=>{data[`${type}s`]=data[`${type}s`].filter(x=>x.id!==id);save();closeSheet();toast('记录已删除')};$('#close-sheet').onclick=closeSheet;}
function unitSheet(){openSheet(`<div class="sheet-handle"></div><h2 class="sheet-title">体重单位</h2><p class="sheet-subtitle">切换时，已有数值会自动换算。</p><div class="activity-options"><button class="activity-option" data-unit="kg">公斤（kg）${data.unit==='kg'?' <span>已选择</span>':''}</button><button class="activity-option" data-unit="lb">磅（lb）${data.unit==='lb'?' <span>已选择</span>':''}</button></div><button class="sheet-secondary" id="close-sheet">取消</button>`);document.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>{if(b.dataset.unit!==data.unit){data.weights=data.weights.map(x=>({...x,value:(data.unit==='kg'?Number(x.value)*2.20462:Number(x.value)/2.20462).toFixed(1)}));data.unit=b.dataset.unit;save()}closeSheet()});$('#close-sheet').onclick=closeSheet;}
$('#previous-month').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);renderCalendar()};$('#next-month').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);renderCalendar()};$('#today-button').onclick=()=>{viewDate=new Date();renderCalendar()};$('#sheet-backdrop').onclick=closeSheet;$('#add-bath').onclick=()=>bathForm();$('#add-weight').onclick=()=>weightForm();$('#quick-weight').onclick=()=>weightForm();$('#add-vaccine').onclick=()=>vaccineForm();$('#bath-reminder').onclick=()=>bathForm();$('#weight-reminder').onclick=()=>weightForm();$('#settings-button').onclick=unitSheet;document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active')});render();
