const DB_KEY='dollar-dog-app:v1';
const SUPABASE_URL='https://ibfshtubugrgkodkjkxm.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_m2RWuLGB500IyExB1muoyA_REwWBDXE';
const fresh=()=>({version:2,profile:{name:'Dollar',avatar:'🐶',unit:'kg'},activities:[],baths:[],weights:[],vaccines:[],ui:{floatingDog:null,footerDog:null,careDog1:null,careDog2:null,careDog3:null,careDog4:null}});
let data=load(),view='home',cursor=new Date(),activeDate=null,cloudUser=null,cloudTimer=null,cloudMessage='';
const cloudClient=window.supabase?.createClient?.(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
function load(){try{const x=JSON.parse(localStorage.getItem(DB_KEY));return x&&x.version?{...fresh(),...x,profile:{...fresh().profile,...x.profile},ui:{...fresh().ui,...x.ui}}:fresh()}catch{return fresh()}}
function save(){data.updatedAt=new Date().toISOString();localStorage.setItem(DB_KEY,JSON.stringify(data));scheduleCloudSync();render()}
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random();
const dateKey=d=>typeof d==='string'?d:new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10);
const today=dateKey(new Date()); const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric'});
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function act(date){return data.activities.find(x=>x.date===date)} function bath(date){return data.baths.find(x=>x.date===date)}
function cal(){const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1).getDay(),n=new Date(y,m+1,0).getDate();let cells='';for(let i=0;i<first;i++)cells+='<div class="day empty"></div>';for(let d=1;d<=n;d++){let k=dateKey(new Date(y,m,d)),a=act(k),b=bath(k),cl=b?'bath':a?a.type:'';cells+=`<button class="day ${cl} ${k===today?'today':''}" onclick="openDay('${k}')"><span>${d}</span>${a&&!b?'<i class="dot"></i>':''}</button>`}return `<div class="calendar-card"><div class="week"><span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span></div><div class="days">${cells}</div><div class="legend"><span class="key"><i class="swatch"></i>遛狗</span><span class="key"><i class="swatch park"></i>狗公园</span><span class="key"><i class="swatch hike"></i>Hiking</span><span class="key"><i class="swatch custom"></i>自定义</span><span class="key"><i class="swatch bath"></i>洗澡</span></div></div>`}
function latestDate(rows){return [...rows].sort((a,b)=>b.date.localeCompare(a.date))[0]?.date}
function summaryCard(title,d,icon){return `<div class="card"><span>${icon} ${title}</span><b>${d?fmt(d):'还没有记录'}</b><small class="muted">${d?'已完成':'添加第一条记录'}</small></div>`}
function home(){let month=data.activities.filter(x=>x.date.slice(0,7)===`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}`);return `<div class="app"><header class="top"><div class="profile"><div class="avatar">${data.profile.avatar}</div><div><div class="name">${esc(data.profile.name)}</div><div class="sub">我的狗狗</div></div></div><button class="round-btn" onclick="profileForm()">⚙</button></header><div class="month-row"><button class="round-btn" onclick="shiftMonth(-1)">‹</button><h1>${cursor.toLocaleDateString('zh-CN',{year:'numeric',month:'long'})}</h1><i class="dog-cutout dog-calendar" aria-hidden="true"></i><button class="round-btn" onclick="shiftMonth(1)">›</button></div>${cal()}${month.length?'' : '<div class="tiny">这个月还没有外出记录</div>'}<div class="notice">${summaryCard('上一次洗澡',latestDate(data.baths),'🫧')}${summaryCard('上一次称重',latestDate(data.weights),'⚖️')}</div></div><button class="fab" onclick="quick()">＋</button>${nav()}`}
function displayWeight(kg){let u=data.profile.unit;let v=u==='kg'?kg:kg*2.20462;return `${Number(v.toFixed(1))} ${u}`}
function nav(){return `<nav class="bottom-nav"><button class="nav ${view==='home'?'active':''}" onclick="go('home')"><i>▦</i>月历</button><button class="nav ${view==='care'?'active':''}" onclick="go('care')"><i>♡</i>健康与护理</button></nav>`}
function carePage(){return `<div class="app"><h1 class="page-title">健康与护理</h1>${bathPage()}${weightPage()}${vaccinePage()}</div>${nav()}`}
function bathPage(){let x=[...data.baths].sort((a,b)=>b.date.localeCompare(a.date));return section('洗澡','新增',"bathForm()",x.length?x.map(r=>record('🫧 洗澡',fmt(r.date),`bathForm('${r.id}')`)).join(''):'<div class="card empty">还没有洗澡记录<br><small>记录每一次舒服的洗澡日</small></div>')}
function weightPage(){let x=[...data.weights].sort((a,b)=>a.date.localeCompare(b.date));let content=x.length>=3?chart(x):'<div class="card empty">记录满 3 次后，这里会显示体重趋势</div>';content+=x.length?[...x].reverse().map(r=>record(displayWeight(r.value),fmt(r.date),`weightForm('${r.id}')`)).join(''):'<div class="card empty">还没有体重记录<br><small>每月称一次，轻松追踪变化</small></div>';return section('体重','新增',"weightForm()",content)}
function vaccinePage(){let x=[...data.vaccines].sort((a,b)=>b.date.localeCompare(a.date));return section('疫苗','新增',"vaccineForm()",x.length?x.map(r=>`<div class="card record" onclick="vaccineForm('${r.id}')"><div><b>${esc(r.name)}</b><div class="meta">接种 ${fmt(r.date)}${r.next?' · 下次 '+fmt(r.next):''}</div></div><span>›</span></div>`).join(''):'<div class="card empty">还没有疫苗记录<br><small>在这里整理接种信息</small></div>')}
function section(t,b,fn,c){return `<section class="section"><div class="section-head"><h2>${t}</h2><button class="add" onclick="${fn}">＋ ${b}</button></div>${c}</section>`}function record(a,b,fn){return `<div class="card record" onclick="${fn}"><div><b>${a}</b><div class="meta">${b}</div></div><span>›</span></div>`}
function chart(x){let vals=x.map(r=>r.value),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,w=300,h=105;let pts=x.map((r,i)=>`${20+i*(w-40)/(x.length-1)},${15+(max-r.value)/range*(h-30)}`).join(' ');return `<div class="card chart"><svg viewBox="0 0 ${w} ${h+25}"><polyline fill="none" stroke="#8170ad" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" points="${pts}"/>${x.map((r,i)=>{let [px,py]=pts.split(' ')[i].split(',');return `<circle cx="${px}" cy="${py}" r="4" fill="#fffdfa" stroke="#8170ad" stroke-width="3"/><text x="${px}" y="${h+16}" text-anchor="middle">${r.date.slice(5)}</text>`}).join('')}</svg></div>`}
function render(){let floaters=view==='home'?'':'<i class="care-dog care-dog-1" aria-hidden="true"></i><i class="care-dog care-dog-2" aria-hidden="true"></i><i class="care-dog care-dog-3" aria-hidden="true"></i><i class="care-dog care-dog-4" aria-hidden="true"></i>';document.getElementById('app').innerHTML=(view==='home'?home():carePage())+floaters}
function initFloatingDog(){if(view==='home'){initDraggableDog('floating-dog','floatingDog',()=>({x:Math.max(132,window.innerWidth-170),y:2}));initDraggableDog('floating-footer-dog','footerDog',()=>({x:0,y:window.innerHeight-188}));return}initDraggableDog('care-dog-1','careDog1',()=>({x:8,y:85}));initDraggableDog('care-dog-2','careDog2',()=>({x:Math.max(0,window.innerWidth-105),y:86}));initDraggableDog('care-dog-3','careDog3',()=>({x:4,y:Math.max(100,window.innerHeight-155)}));initDraggableDog('care-dog-4','careDog4',()=>({x:Math.max(0,window.innerWidth-108),y:Math.max(90,window.innerHeight-170)}))}
function initDraggableDog(elementId,stateKey,defaults){let dog=document.getElementById(elementId);if(!dog)return;let saved=data.ui?.[stateKey],initial=defaults(),x=saved?.x??initial.x,y=saved?.y??initial.y;let place=()=>{x=Math.min(Math.max(0,x),window.innerWidth-dog.offsetWidth);y=Math.min(Math.max(0,y),window.innerHeight-dog.offsetHeight);dog.style.left=`${x}px`;dog.style.top=`${y}px`};place();let grabX=0,grabY=0;dog.addEventListener('pointerdown',e=>{grabX=e.clientX-x;grabY=e.clientY-y;dog.setPointerCapture(e.pointerId);dog.classList.add('dragging')});dog.addEventListener('pointermove',e=>{if(!dog.hasPointerCapture(e.pointerId))return;x=e.clientX-grabX;y=e.clientY-grabY;place()});let finish=e=>{if(!dog.hasPointerCapture(e.pointerId))return;dog.releasePointerCapture(e.pointerId);dog.classList.remove('dragging');data.ui[stateKey]={x:Math.round(x),y:Math.round(y)};localStorage.setItem(DB_KEY,JSON.stringify(data))};dog.addEventListener('pointerup',finish);dog.addEventListener('pointercancel',finish)}
function go(v){view=v;render()}function shiftMonth(n){cursor=new Date(cursor.getFullYear(),cursor.getMonth()+n,1);render()}
function modal(html){document.getElementById('modal-root').innerHTML=`<div class="overlay" onclick="if(event.target===this)closeModal()"><section class="sheet">${html}</section></div>`}function closeModal(){document.getElementById('modal-root').innerHTML=''}
function quick(){activeDate=today;daySheet()} function openDay(d){activeDate=d;daySheet()}
function daySheet(){let a=act(activeDate),b=bath(activeDate);modal(`<div class="handle"></div><div class="sheet-top"><h2>${fmt(activeDate)}</h2><button class="close" onclick="closeModal()">×</button></div>${a||b?`<div class="day-detail-head">${a?`<button class="choice ${a.type}" onclick="activityForm('${a.id}')">${esc(activityDisplay(a))} <span>编辑 ›</span></button>`:''}${b?`<button class="choice bath" onclick="bathForm('${b.id}')">洗澡 <span>编辑 ›</span></button>`:''}</div><div class="actions"><button class="primary" onclick="dayDetail('${activeDate}')">当天详情</button></div>`:`<div class="choices"><button class="choice walk" onclick="activityForm(null,'walk')">遛狗 <span>简单 · 开心果绿</span></button><button class="choice park" onclick="activityForm(null,'park')">狗公园 <span>中等 · 暖棕</span></button><button class="choice hike" onclick="activityForm(null,'hike')">Hiking <span>难 · 天蓝色</span></button><button class="choice custom" onclick="activityForm(null,'custom')">自定义 <span>淡黄色</span></button><button class="choice bath" onclick="bathForm()">洗澡 <span>🫧 泡泡</span></button></div>`}`)}
function label(t){return({walk:'遛狗',park:'狗公园',hike:'Hiking',custom:'自定义'})[t]}
function activityDisplay(a){return a.type==='custom'?(a.customLabel||'自定义'):label(a.type)}
function dayDetail(d){let a=act(d),b=bath(d);modal(`<div class="handle"></div><div class="sheet-top"><h2>${fmt(d)} 的记录</h2><button class="close" onclick="closeModal()">×</button></div>${a?`<div class="record card"><div><b>${esc(activityDisplay(a))}</b><div class="meta">${a.intensity}强度 · 已发生</div></div><button class="text-btn" onclick="activityForm('${a.id}')">编辑</button></div>`:''}${b?`<div class="record card"><div><b>洗澡</b><div class="meta">已完成</div></div><button class="text-btn" onclick="bathForm('${b.id}')">编辑</button></div>`:''}`)}
function activityForm(editId,type){let r=editId?data.activities.find(x=>x.id===editId):{date:activeDate||today,type,customLabel:''};modal(`<div class="handle"></div><div class="sheet-top"><h2>${editId?'编辑外出活动':'记录外出活动'}</h2><button class="close" onclick="closeModal()">×</button></div><form class="form" onsubmit="saveActivity(event,'${editId||''}')"><label>活动</label><select name="type" onchange="toggleCustomActivity(this)"><option value="walk" ${r.type==='walk'?'selected':''}>遛狗 · 简单</option><option value="park" ${r.type==='park'?'selected':''}>狗公园 · 中等</option><option value="hike" ${r.type==='hike'?'selected':''}>Hiking · 难</option><option value="custom" ${r.type==='custom'?'selected':''}>自定义 · 淡黄色</option></select><div class="custom-activity-field" style="display:${r.type==='custom'?'block':'none'}"><label>做了什么</label><input name="customLabel" maxlength="24" value="${esc(r.customLabel||'')}" placeholder="例如：去宠物店、朋友家玩"></div><label>日期</label><input type="date" name="date" max="${today}" value="${r.date}" required><div class="actions"><button class="primary">保存</button>${editId?`<button type="button" class="danger" onclick="confirmDelete('activity','${editId}')">删除</button>`:''}</div></form>`) }
function toggleCustomActivity(select){let field=select.form.querySelector('.custom-activity-field'),input=field.querySelector('input');field.style.display=select.value==='custom'?'block':'none';input.required=select.value==='custom'}
function saveActivity(e,id0){e.preventDefault();let f=new FormData(e.target),type=f.get('type'),customLabel=f.get('customLabel').trim();if(type==='custom'&&!customLabel)return;let x={id:id0||id(),date:f.get('date'),type,customLabel:type==='custom'?customLabel:'',intensity:{walk:'简单',park:'中等',hike:'难',custom:'自定义'}[type],updatedAt:new Date().toISOString()};if(id0)Object.assign(data.activities.find(r=>r.id===id0),x);else data.activities.push({...x,createdAt:x.updatedAt});closeModal();save()}
function bathForm(editId){let r=editId?data.baths.find(x=>x.id===editId):{date:activeDate||today};modal(`<div class="handle"></div><div class="sheet-top"><h2>${editId?'编辑洗澡记录':'记录洗澡'}</h2><button class="close" onclick="closeModal()">×</button></div><form class="form" onsubmit="saveBath(event,'${editId||''}')"><label>洗澡日期</label><input type="date" name="date" max="${today}" value="${r.date}" required><div class="actions"><button class="primary">保存</button>${editId?`<button type="button" class="danger" onclick="confirmDelete('bath','${editId}')">删除</button>`:''}</div></form>`) }function saveBath(e,id0){e.preventDefault();let f=new FormData(e.target),x={id:id0||id(),date:f.get('date'),updatedAt:new Date().toISOString()};if(id0)Object.assign(data.baths.find(r=>r.id===id0),x);else data.baths.push({...x,createdAt:x.updatedAt});closeModal();save()}
function weightForm(editId){let r=editId?data.weights.find(x=>x.id===editId):{date:today,value:''},unit=data.profile.unit;let shown=r.value===''?'':(unit==='kg'?r.value:(r.value*2.20462).toFixed(1));modal(`<div class="handle"></div><div class="sheet-top"><h2>${editId?'编辑体重':'记录体重'}</h2><button class="close" onclick="closeModal()">×</button></div><form class="form" onsubmit="saveWeight(event,'${editId||''}')"><label>体重 (${unit})</label><input type="number" step="0.1" min="0.1" name="value" value="${shown}" required><label>日期</label><input type="date" name="date" max="${today}" value="${r.date}" required><div class="actions"><button class="primary">保存</button>${editId?`<button type="button" class="danger" onclick="confirmDelete('weight','${editId}')">删除</button>`:''}</div></form>`) }function saveWeight(e,id0){e.preventDefault();let f=new FormData(e.target),v=Number(f.get('value'));if(data.profile.unit==='lb')v/=2.20462;let x={id:id0||id(),date:f.get('date'),value:v,updatedAt:new Date().toISOString()};if(id0)Object.assign(data.weights.find(r=>r.id===id0),x);else data.weights.push({...x,createdAt:x.updatedAt});closeModal();save()}
function vaccineForm(editId){let r=editId?data.vaccines.find(x=>x.id===editId):{name:'',date:today,next:'',note:''};modal(`<div class="handle"></div><div class="sheet-top"><h2>${editId?'编辑疫苗':'新增疫苗'}</h2><button class="close" onclick="closeModal()">×</button></div><form class="form" onsubmit="saveVaccine(event,'${editId||''}')"><label>疫苗名称</label><input name="name" value="${esc(r.name)}" required><label>接种日期</label><input type="date" name="date" max="${today}" value="${r.date}" required><label>下次接种日期</label><input type="date" name="next" value="${r.next||''}"><label>备注</label><textarea name="note">${esc(r.note||'')}</textarea><div class="actions"><button class="primary">保存</button>${editId?`<button type="button" class="danger" onclick="confirmDelete('vaccine','${editId}')">删除</button>`:''}</div></form>`) }function saveVaccine(e,id0){e.preventDefault();let f=new FormData(e.target),x={id:id0||id(),name:f.get('name').trim(),date:f.get('date'),next:f.get('next'),note:f.get('note').trim(),updatedAt:new Date().toISOString()};if(id0)Object.assign(data.vaccines.find(r=>r.id===id0),x);else data.vaccines.push({...x,createdAt:x.updatedAt});closeModal();save()}
function confirmDelete(kind,i){modal(`<div class="handle"></div><div class="confirm"><h2>确认删除？</h2><p>这条记录将从 Dollar 中移除，删除后无法恢复。</p><div class="actions"><button class="secondary" onclick="closeModal()">取消</button><button class="danger" onclick="doDelete('${kind}','${i}')">确认删除</button></div></div>`)}function doDelete(k,i){let map={activity:'activities',bath:'baths',weight:'weights',vaccine:'vaccines'};data[map[k]]=data[map[k]].filter(x=>x.id!==i);closeModal();save()}
function cloudSettings(){if(!cloudClient)return `<div class="cloud-box"><b>云端同步暂不可用</b><small>请检查网络后再试</small></div>`;if(cloudUser)return `<div class="cloud-box connected"><div><b>云端同步已开启</b><small>${esc(cloudUser.email||'已连接')}</small></div><button type="button" class="text-btn" onclick="syncCloudNow()">立即同步</button><button type="button" class="text-btn" onclick="signOutCloud()">退出</button></div>`;return `<div class="cloud-box"><b>云端同步</b><small>用邮箱登录后，在你的设备间同步记录</small><input id="cloud-email" type="email" inputmode="email" autocomplete="email" placeholder="你的邮箱"><button type="button" class="secondary cloud-action" onclick="startCloudSync()">开启云端同步</button>${cloudMessage?`<small class="cloud-message">${esc(cloudMessage)}</small>`:''}</div>`}
function profileForm(){modal(`<div class="handle"></div><div class="sheet-top"><h2>设置</h2><button class="close" onclick="closeModal()">×</button></div><form class="form" onsubmit="saveProfile(event)"><label>名字</label><input name="name" value="${esc(data.profile.name)}" required><label>默认头像</label><select name="avatar"><option ${data.profile.avatar==='🐶'?'selected':''}>🐶</option><option ${data.profile.avatar==='🐾'?'selected':''}>🐾</option><option ${data.profile.avatar==='🦮'?'selected':''}>🦮</option></select><label>体重单位</label><select name="unit"><option value="kg" ${data.profile.unit==='kg'?'selected':''}>kg</option><option value="lb" ${data.profile.unit==='lb'?'selected':''}>lb</option></select>${cloudSettings()}<div class="actions"><button class="primary">保存设置</button></div></form>`) }function saveProfile(e){e.preventDefault();let f=new FormData(e.target);data.profile={...data.profile,name:f.get('name').trim(),avatar:f.get('avatar'),unit:f.get('unit')};closeModal();save()}
function cloudSnapshot(){let {ui,...snapshot}=data;return {...snapshot,version:2}}
function hasRecords(snapshot){return ['activities','baths','weights','vaccines'].some(k=>(snapshot[k]||[]).length)}
function hydrateCloud(snapshot){let localUi=data.ui;data={...fresh(),...snapshot,profile:{...fresh().profile,...snapshot.profile},ui:{...fresh().ui,...localUi}};localStorage.setItem(DB_KEY,JSON.stringify(data));render()}
async function pullCloud(){if(!cloudClient||!cloudUser)return;let {data:row,error}=await cloudClient.from('dollar_profiles').select('data').eq('user_id',cloudUser.id).maybeSingle();if(error){cloudMessage='读取云端数据失败，请稍后重试';return}if(row?.data){hydrateCloud(row.data);cloudMessage='已从云端同步'}else await pushCloudNow()}
async function pushCloudNow(){if(!cloudClient||!cloudUser)return;let {error}=await cloudClient.from('dollar_profiles').upsert({user_id:cloudUser.id,data:cloudSnapshot(),updated_at:new Date().toISOString()});cloudMessage=error?'同步失败，请检查网络':'已同步到云端';if(!error&&document.querySelector('.overlay'))profileForm()}
function scheduleCloudSync(){if(!cloudUser)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(pushCloudNow,700)}
async function syncCloudNow(){await pushCloudNow()}
async function startCloudSync(){let email=document.getElementById('cloud-email')?.value.trim();if(!email){cloudMessage='请输入邮箱';profileForm();return}let {error}=await cloudClient.auth.signInWithOtp({email,options:{emailRedirectTo:'https://dollar-lyart.vercel.app'}});cloudMessage=error?'邮件发送失败，请稍后重试':'登录链接已发送，请打开邮箱完成一次登录';profileForm()}
async function signOutCloud(){await cloudClient?.auth.signOut();cloudUser=null;cloudMessage='已退出云端同步，本机记录仍会保留';profileForm()}
async function initCloud(){if(!cloudClient)return;let {data:sessionData}=await cloudClient.auth.getSession();if(sessionData.session){cloudUser=sessionData.session.user;await pullCloud()}cloudClient.auth.onAuthStateChange((event,session)=>{cloudUser=session?.user||null;if(event==='SIGNED_IN')setTimeout(pullCloud,0);if(event==='SIGNED_OUT')cloudMessage='已退出云端同步'})}
window.addEventListener('online',()=>{if(cloudUser)pushCloudNow()});
render();initCloud();
